"""Ajout modèle FicheSecurite

Revision ID: 3a9b3082a992
Revises: 
Create Date: 2025-07-18 15:46:35.502045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9b3082a992'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiche_securite', schema=None) as batch_op:
        batch_op.alter_column('titre',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=260),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiche_securite', schema=None) as batch_op:
        batch_op.alter_column('titre',
               existing_type=sa.String(length=260),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
