"""Ajout champ photo_poste à FicheSecurite

Revision ID: 73668341303d
Revises: 9a29eb26b2ac
Create Date: 2025-07-20 15:09:23.446445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73668341303d'
down_revision = '9a29eb26b2ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiche_securite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_poste', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiche_securite', schema=None) as batch_op:
        batch_op.drop_column('photo_poste')

    # ### end Alembic commands ###
