"""Correction suppression poste_id

Revision ID: 9a29eb26b2ac
Revises: e5ecd2c0196a
Create Date: 2025-07-18 23:14:13.010339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a29eb26b2ac'
down_revision = 'e5ecd2c0196a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('poste_id')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poste_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'poste', ['poste_id'], ['id'])

    # ### end Alembic commands ###
