"""Suppression des champs abonnements booléens

Revision ID: e5ecd2c0196a
Revises: 3a9b3082a992
Create Date: 2025-07-18 22:51:05.252244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ecd2c0196a'
down_revision = '3a9b3082a992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('securite')
        batch_op.drop_column('qualite')
        batch_op.drop_column('environnement')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('environnement', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('qualite', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('securite', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
