"""Ajout du champ arbre_json

Revision ID: f62b2608b11e
Revises: 73668341303d
Create Date: 2025-07-21 17:56:28.680711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62b2608b11e'
down_revision = '73668341303d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accident_travail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arbre_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accident_travail', schema=None) as batch_op:
        batch_op.drop_column('arbre_json')

    # ### end Alembic commands ###
